# Generated by Django 3.0 on 2020-03-20 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200320_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='owner',
            new_name='owners',
        ),
    ]
