# Generated by Django 3.0 on 2020-03-20 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200320_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='owners',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='articles.Owner'),
        ),
    ]
