# Generated by Django 3.0 on 2020-03-20 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200320_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='owners',
        ),
    ]
