# Generated by Django 3.0 on 2020-03-20 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20200320_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='owner',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
