# Generated by Django 3.0 on 2020-03-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20200320_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='gender',
            field=models.CharField(choices=[('KAN', 'KAN'), ('SZUKA', 'SZUKA')], default='', max_length=5),
        ),
    ]
