# Generated by Django 3.0 on 2020-03-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_article_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='gender',
            field=models.CharField(choices=[('Kan', 'Kan'), ('Szuka', 'Szuka')], default='', max_length=5),
        ),
    ]
