# Generated by Django 3.0 on 2020-03-20 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0014_auto_20200320_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='dog_number',
            field=models.CharField(default='', max_length=10, unique=True),
        ),
    ]
