# Generated by Django 3.0 on 2020-03-20 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_article_dog_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='body',
        ),
    ]
