# Generated by Django 3.0 on 2020-03-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='percent',
            field=models.CharField(default='', max_length=200),
        ),
    ]
