# Generated by Django 3.0 on 2020-03-23 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_donation_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='max_amount',
            field=models.IntegerField(default=100000),
        ),
    ]
