# Generated by Django 3.0 on 2020-03-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0025_auto_20200324_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shortcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('body', models.TextField()),
            ],
        ),
    ]
