# Generated by Django 3.0 on 2020-03-25 05:52

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0028_auto_20200325_0651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scripts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('shortcode', models.CharField(default='', max_length=100)),
                ('body', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
