# Generated by Django 3.0 on 2020-03-25 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0029_scripts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scripts',
            name='body',
            field=models.TextField(),
        ),
    ]
