# Generated by Django 3.0 on 2020-03-26 16:51

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0031_join'),
    ]

    operations = [
        migrations.AlterField(
            model_name='join',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
