# Generated by Django 3.0 on 2020-03-26 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0032_auto_20200326_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='join',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='join',
            name='thumb',
        ),
    ]
